application: your-app-id
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:
# Endpoints handler: this must be /_ah/spi for Endpoints, NOT /_ah/api!
- url: /_ah/spi/.*
  script: noten_api.APPLICATION

- url: /(.+)
  static_files: frontend/dist/\1
  upload: frontend/dist/(.*)

- url: /
  static_files: frontend/dist/index.html
  upload: frontend/dist/index.html

libraries:
- name: pycrypto
  version: latest
- name: endpoints
  version: 1.0
